language: node_js
node_js:
    - "10"
# env:
    # - CXX=g++-4.8
# addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - g++-4.8
install:
    - phpenv global 7.1
    - composer require --dev phpdocumentor/phpdocumentor dev-master
#    - composer require cvuorinen/phpdoc-markdown-public
#    - sed -i '14s/.*//' vendor/cvuorinen/phpdoc-markdown-public/composer.json
#    - composer require ravenflux/sort-functions:dev-master
#    - composer require dpolac/twig-lambda
    - composer require picocms/pico
    - sed -i '36s/.*/public function __construct()/' vendor/picocms/pico/lib/PicoTwigExtension.php
    - sed -i '38s/.*//' vendor/picocms/pico/lib/PicoTwigExtension.php
    - npm install -g vuepress
before_script:
    - git clone https://github.com/PandoraTeam/pandora3-Core.git src/Core
    - git clone --recurse-submodules https://github.com/PandoraTeam/pandora3-Libs.git src/Libs
script:
    - php vendor/bin/phpdoc -d src -t docs/api --title "Pandora API documentation" --template="templates/markdown-pandora"
    # - php vendor/bin/phpdoc -d src -t docs/api --title "Pandora API documentation" --template="vendor/cvuorinen/phpdoc-markdown-public/data/templates/markdown-public"
    - npm run docs:build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: NesCafe62/pandora3
    keep-history: true
    target-branch: master
    on:
        branch: master
