# language: node_js
# node_js:
#    - "10"

language: php
php:
    - '7.0'

install:
#    - phpenv global 7.2
    - composer install --no-interaction
    - composer show -i phpdocumentor/phpdocumentor
#    - composer require --dev phpdocumentor/phpdocumentor dev-master
#    - composer require cvuorinen/phpdoc-markdown-public
#    - sed -i '14s/.*//' vendor/cvuorinen/phpdoc-markdown-public/composer.json
#    - composer require ravenflux/sort-functions:dev-master
#    - composer require dpolac/twig-lambda
#    - composer require picocms/pico
    - npm install -g vuepress

before_script:
    - sed -i '36s/.*/public function __construct()/' vendor/picocms/pico/lib/PicoTwigExtension.php
    - sed -i '38s/.*//' vendor/picocms/pico/lib/PicoTwigExtension.php
    - git clone https://github.com/PandoraTeam/pandora3-Core.git src/Core
    - git clone --recurse-submodules https://github.com/PandoraTeam/pandora3-Libs.git src/Libs

script:
    - vendor/bin/phpdoc -d src -t docs/api --title "Pandora API documentation" --template="templates/markdown-pandora"
    # - php vendor/bin/phpdoc -d src -t docs/api --title "Pandora API documentation" --template="vendor/cvuorinen/phpdoc-markdown-public/data/templates/markdown-public"
    - npm run docs:build

cache:
    directories:
        - $HOME/.composer/cache
        - "node_modules"

notifications:
    email: false

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: NesCafe62/pandora3
    keep-history: true
    target-branch: master
    on:
        branch: master
